In [27]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

In [40]:
vacweather = pd.read_csv("Weather.csv")
vacweather

,City,City Number,Latitude,Longitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph)
0,Muros,3115824,42.78,-9.06,66.99,81,18,5.99
1,Hervey Bay,2146219,-25.30,152.85,69.01,69,66,4.00
2,Saint-Philippe,935215,-21.36,55.77,60.26,77,90,14.99
3,Jamestown,5122534,42.10,-79.24,66.09,93,90,6.93
4,Nanortalik,3421765,60.14,-45.24,45.05,90,100,5.75
...,...,...,...,...,...,...,...,...
453,Vágur,2610806,61.47,-6.81,50.72,89,10,12.73
454,Sistranda,3139597,63.73,8.83,51.89,100,75,12.75
455,Porto Velho,3662762,-8.76,-63.90,82.40,42,6,2.24
456,Havelock,4470244,34.88,-76.90,80.31,88,90,5.82
457,Itupiranga,3397851,-5.13,-49.33,78.80,65,38,1.57

In [39]:
gmaps.configure(g_key)

locations = vacweather[["Latitude", "Longitude"]]
humidity = vacweather["Humidity (%)"]


fig = gmaps.figure(center=(15, 25), zoom_level=2)
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity=np.max(humidity), point_radius=2)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [52]:
temp_filt = (vacweather['Temperature (F)']>80)
windspeed_filt = vacweather['Wind Speed (mph)']<15
cloud_filt = vacweather["Cloudiness (%)"] == 0
filters = temp_filt & windspeed_filt & cloud_filt
vacweather_filt = vacweather[filters]
#vacweather_filt = vacweather_filt.dropna()
#vacweather_filt = vacweather_filt.reset_index()
vacweather_filt

,City,City Number,Latitude,Longitude,Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph)
311,Tripoli,2210247,32.88,13.19,87.31,31,0,5.70
335,Misratah,2214846,32.38,15.09,80.58,66,0,10.71
338,Khorramshahr,127319,30.44,48.17,96.80,23,0,11.41
342,Sakakah,102527,29.97,40.21,86.00,13,0,14.99
344,Sabha,2212775,27.04,14.43,84.07,14,0,10.29